Traceback (most recent call last):
  File "C:\Users\Fedi Arta\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Fedi Arta\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Fedi Arta\AppData\Roaming\Python\Python310\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\Fedi Arta\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Fedi Arta\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Fedi Arta\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Fedi Arta\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = pd.read_csv("https://github.com/Fediarta/psd/blob/gh-pages/PSD.csv", low_memory = False, encoding='utf8')
df.head()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mParserError[0m                               Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_csv[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mhttps://github.com/Fediarta/psd/blob/gh-pages/PSD.csv[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mlow_memory[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mutf8[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m df[38;5;241m.[39mhead()

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py:1026[0m, in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)[0m
[0;32m   1013[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[0;32m   1014[0m     dialect,
[0;32m   1015[0m     delimiter,
[1;32m   (...)[0m
[0;32m   1022[0m     dtype_backend[38;5;241m=[39mdtype_backend,
[0;32m   1023[0m )
[0;32m   1024[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[1;32m-> 1026[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py:626[0m, in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    623[0m     [38;5;28;01mreturn[39;00m parser
[0;32m    625[0m [38;5;28;01mwith[39;00m parser:
[1;32m--> 626[0m     [38;5;28;01mreturn[39;00m [43mparser[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py:1923[0m, in [0;36mTextFileReader.read[1;34m(self, nrows)[0m
[0;32m   1916[0m nrows [38;5;241m=[39m validate_integer([38;5;124m"[39m[38;5;124mnrows[39m[38;5;124m"[39m, nrows)
[0;32m   1917[0m [38;5;28;01mtry[39;00m:
[0;32m   1918[0m     [38;5;66;03m# error: "ParserBase" has no attribute "read"[39;00m
[0;32m   1919[0m     (
[0;32m   1920[0m         index,
[0;32m   1921[0m         columns,
[0;32m   1922[0m         col_dict,
[1;32m-> 1923[0m     ) [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43m  [49m[38;5;66;43;03m# type: ignore[attr-defined][39;49;00m
[0;32m   1924[0m [43m        [49m[43mnrows[49m
[0;32m   1925[0m [43m    [49m[43m)[49m
[0;32m   1926[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[0;32m   1927[0m     [38;5;28mself[39m[38;5;241m.[39mclose()

File [1;32m~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:239[0m, in [0;36mCParserWrapper.read[1;34m(self, nrows)[0m
[0;32m    236[0m         data [38;5;241m=[39m _concatenate_chunks(chunks)
[0;32m    238[0m     [38;5;28;01melse[39;00m:
[1;32m--> 239[0m         data [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_reader[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m
[0;32m    240[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[0;32m    241[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_first_chunk:

File [1;32mparsers.pyx:820[0m, in [0;36mpandas._libs.parsers.TextReader.read[1;34m()[0m

File [1;32mparsers.pyx:914[0m, in [0;36mpandas._libs.parsers.TextReader._read_rows[1;34m()[0m

File [1;32mparsers.pyx:891[0m, in [0;36mpandas._libs.parsers.TextReader._check_tokenize_status[1;34m()[0m

File [1;32mparsers.pyx:2061[0m, in [0;36mpandas._libs.parsers.raise_parser_error[1;34m()[0m

[1;31mParserError[0m: Error tokenizing data. C error: Expected 1 fields in line 41, saw 28


